### ISSUE TITLE
Error Message during the package installation

### ISSUE THREAD

**Issue by smuthuganesh** [rakutentech/go-nozzle#2]
bash-4.1$ go get github.com/rakutentech/go-nozzle
 # github.com/rakutentech/go-nozzle
work/src/github.com/rakutentech/go-nozzle/detector.go:75: undefined: websocket.CloseError
work/src/github.com/rakutentech/go-nozzle/detector.go:76: t.Code undefined (type error has no field or method Code)
bash-4.1$

**Comment by tcnksm** [comment]
Hi, maybe you have old version of `websocket` package,

Could you try the following command,

``` bash
$ go get -v -u github.com/rakutentech/go-nozzle
```

**Comment by smuthuganesh** [comment]
Hi,

Thanks, I am not getting the above error now.

I have created a new golang workspace and could download the latest version of packages.  It worked.

**Comment by tcnksm** [comment]
Great !
I'll close this
